import { Link } from 'wouter';
import { Activity, ArrowRight, BarChart3, Database, Hash, Layers3, LoaderCircle, Target } from 'lucide-react';
import { trpc } from '@/lib/trpc';
import { KineticSongHud } from '@/components/ui/kinetic-song-hud';
import { AppFooter, AppHeader } from '@/components/AppChrome';

function percent(value: number) { return `${Math.round(value * 100)}%`; }
function MetricCard({ label, explanation, value, tone = 'gold' }: { label: string; explanation: string; value: number; tone?: 'gold' | 'green' }) {
  const barColor = tone === 'green' ? 'bg-emerald-400' : 'bg-[#e0ae55]';
  return <div className="rounded-xl border border-white/[.08] bg-[#0d151f] p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-slate-200">{label}</span><span className="font-mono text-sm font-semibold text-[#edc675]">{percent(value)}</span></div><p className="mt-2 min-h-10 text-[11px] leading-5 text-slate-500">{explanation}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.07]"><div className={`h-full rounded-full ${barColor} transition-all duration-700`} style={{ width: `${Math.max(2, value * 100)}%` }} /></div></div>;
}

export default function Stats() {
  const evaluation = trpc.songs.evaluation.useQuery();
  const data = evaluation.data;
  const keywordMap = data?.summary.keyword.map ?? 0;
  const semanticMap = data?.summary.semantic.map ?? 0;
  const keywordWins = keywordMap >= semanticMap;
  const cards = [
    { label: 'เพลงในคลัง', value: data?.indexStats.documents, icon: Database, detail: 'เพลงที่ระบบค้นหาได้' },
    { label: 'คำศัพท์ที่รู้จัก', value: data?.indexStats.vocabulary, icon: Hash, detail: 'คำหลังแยกจากชุดเพลง' },
    { label: 'รายการในดัชนี', value: data?.indexStats.postings, icon: Layers3, detail: 'คำเชื่อมกับตำแหน่งในเพลง' },
    { label: 'คำค้นทดสอบ', value: data?.rows.length, icon: Target, detail: 'ตัวอย่างที่มีคำตอบกำกับ' },
  ];
  return <div className="min-h-screen bg-[#080d14] text-white"><AppHeader /><main className="container pb-14 pt-7 md:pb-20 md:pt-10">
    <KineticSongHud eyebrow="ประสิทธิภาพของระบบค้นหา" title="วัดผลให้เห็นว่าเพลงตรงแค่ไหน" description="แดชบอร์ดนี้เปรียบเทียบการค้นจากเนื้อเพลงกับการค้นตามอารมณ์ ด้วยชุดคำค้นทดสอบและคำตอบอ้างอิง" badge={data?.indexStats.embeddingModel === 'fallback mood scorer' ? 'SEMANTIC · FALLBACK' : 'IR EVALUATION'}>
      <div className="flex items-center gap-3"><div className="grid size-12 shrink-0 place-items-center rounded-xl border border-[#e0ae55]/25 bg-[#e0ae55]/10 text-[#e0ae55]"><Activity size={20} /></div><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">CURRENT READOUT</p>{evaluation.isLoading ? <p className="mt-1 flex items-center gap-2 text-sm text-slate-300"><LoaderCircle size={14} className="animate-spin" />กำลังคำนวณผลทดสอบ…</p> : <p className="mt-1 text-sm font-semibold text-white">{keywordWins ? 'คำค้นตรง ๆ เรียงได้แม่นกว่า' : 'ค้นตามอารมณ์ทำได้ใกล้เคียง'}</p>}</div></div>
      {!evaluation.isLoading && <div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-widest text-slate-500">LYRIC MAP</p><p className="mt-1 text-2xl font-semibold text-[#edc675]">{percent(keywordMap)}</p></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-widest text-slate-500">MOOD MAP</p><p className="mt-1 text-2xl font-semibold text-emerald-300">{percent(semanticMap)}</p></div></div>}
    </KineticSongHud>

    <section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(item => <article key={item.label} className="rounded-2xl border border-white/[.08] bg-[#101823] p-5"><div className="flex items-center justify-between"><span className="text-xs font-medium text-slate-400">{item.label}</span><span className="grid size-9 place-items-center rounded-xl border border-[#d7aa57]/15 bg-[#d7aa57]/[.08] text-[#d7aa57]"><item.icon size={16} /></span></div><div className="mt-5 font-mono text-3xl font-semibold tracking-tight text-white">{item.value == null ? '—' : item.value.toLocaleString()}</div><p className="mt-1 text-[11px] text-slate-500">{item.detail}</p></article>)}</section>

    <section className="mt-8 grid gap-4 xl:grid-cols-2">
      <article className="rounded-2xl border border-[#d7aa57]/20 bg-gradient-to-br from-[#182231] to-[#101823] p-5 sm:p-7"><div className="flex items-start justify-between"><div><span className="rounded-full border border-[#d7aa57]/20 bg-[#d7aa57]/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-[#edc675]">01 / LYRICS</span><h2 className="mt-4 text-xl font-semibold text-white" style={{ fontFamily: 'Taviraj, serif' }}>ค้นจากคำที่จำได้</h2><p className="mt-1 text-xs text-slate-500">TF-IDF · cosine similarity · phrase match</p></div><BarChart3 className="text-[#d7aa57]" size={19} /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><MetricCard label="ความตรง" explanation="สัดส่วนผลลัพธ์ที่เกี่ยวข้องใน 5 อันดับแรก" value={data?.summary.keyword.precision ?? 0} /><MetricCard label="ความครอบคลุม" explanation="สัดส่วนเพลงที่เกี่ยวข้องซึ่งระบบค้นพบ" value={data?.summary.keyword.recall ?? 0} /><MetricCard label="คะแนนสมดุล F1" explanation="ภาพรวมของ precision และ recall" value={data?.summary.keyword.f1 ?? 0} /></div><div className="mt-5 border-t border-white/10 pt-4 text-xs leading-6 text-slate-400">เหมาะเมื่อจำคำหรือท่อนเพลงได้ เช่น “ทิ้งไว้กลางทาง”</div></article>
      <article className="rounded-2xl border border-emerald-300/15 bg-gradient-to-br from-[#14221f] to-[#101823] p-5 sm:p-7"><div className="flex items-start justify-between"><div><span className="rounded-full border border-emerald-300/15 bg-emerald-300/[.08] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-200">02 / MOOD</span><h2 className="mt-4 text-xl font-semibold text-white" style={{ fontFamily: 'Taviraj, serif' }}>ค้นจากความรู้สึก</h2><p className="mt-1 text-xs text-slate-500">Multilingual embeddings · mood fallback</p></div><Activity className="text-emerald-300" size={19} /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><MetricCard tone="green" label="ความตรง" explanation="สัดส่วนผลลัพธ์ที่เกี่ยวข้องใน 5 อันดับแรก" value={data?.summary.semantic.precision ?? 0} /><MetricCard tone="green" label="ความครอบคลุม" explanation="สัดส่วนเพลงที่เกี่ยวข้องซึ่งระบบค้นพบ" value={data?.summary.semantic.recall ?? 0} /><MetricCard tone="green" label="คะแนนสมดุล F1" explanation="ภาพรวมของ precision และ recall" value={data?.summary.semantic.f1 ?? 0} /></div><div className="mt-5 border-t border-white/10 pt-4 text-xs leading-6 text-slate-400">เหมาะเมื่อจำได้แค่อารมณ์หรือสถานการณ์ เช่น “เพลงเศร้าตอนฝนตก”</div></article>
    </section>

    <section className="mt-4 rounded-2xl border border-white/[.08] bg-[#101823] p-5 sm:p-7"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#d7aa57]">RANKING QUALITY</div><h2 className="mt-2 text-xl font-semibold text-white" style={{ fontFamily: 'Taviraj, serif' }}>เพลงที่ใช่ขึ้นมาอยู่ต้น ๆ หรือไม่?</h2></div><span className="w-fit rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-[10px] text-slate-400">{data?.rows.length ?? '…'} evaluation queries</span></div><p className="mt-2 text-xs leading-6 text-slate-500">Precision@k แสดงสัดส่วนเพลงที่เกี่ยวข้องใน k อันดับแรก ส่วน MAP ประเมินลำดับของเพลงที่เกี่ยวข้องในผลลัพธ์ที่ระบบส่งกลับ</p>
      <div className="mt-6 grid gap-4 md:grid-cols-2">{[{ name: 'ค้นจากเนื้อเพลง', color: 'bg-[#e0ae55]', curve: data?.curve.keyword ?? [], score: keywordMap }, { name: 'ค้นตามอารมณ์', color: 'bg-emerald-400', curve: data?.curve.semantic ?? [], score: semanticMap }].map(chart => <div key={chart.name} className="rounded-xl border border-white/[.06] bg-[#0b121b] p-4"><div className="flex items-center justify-between gap-2 text-xs font-semibold text-slate-200"><span>{chart.name}</span><span className="font-mono text-slate-400">MAP {percent(chart.score)}</span></div><div className="mt-5 flex h-28 items-end gap-3">{chart.curve.map(point => <div key={point.k} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className={`w-full max-w-20 rounded-t-md ${chart.color} opacity-90 transition-all`} style={{ height: `${Math.max(4, point.precision * 82)}%` }} /><span className="text-[10px] text-slate-500">P@{point.k}</span></div>)}</div></div>)}</div>
    </section>

    <details className="mt-4 overflow-hidden rounded-2xl border border-white/[.08] bg-[#101823]"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-5 text-sm font-semibold text-slate-200 sm:px-7"><span>รายละเอียดคำค้นทดสอบ</span><span className="font-mono text-[10px] text-slate-500">20 QUERIES</span></summary><div className="border-t border-white/[.08] p-4 sm:p-6"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead><tr className="border-b border-white/10 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-3 py-3">คำค้น</th><th className="px-3 py-3">โหมด</th><th className="px-3 py-3">P@5</th><th className="px-3 py-3">R@5</th><th className="px-3 py-3">F1@5</th><th className="px-3 py-3">อันดับ 1</th></tr></thead><tbody className="divide-y divide-white/[.06]">{(data?.rows ?? []).map(row => <tr key={row.query} className="text-slate-300"><td className="px-3 py-3 font-medium">{row.query}</td><td className="px-3 py-3 text-slate-500">{row.mode === 'mood' ? 'อารมณ์' : 'เนื้อเพลง'}</td><td className="px-3 py-3 font-mono">{percent(row.precision)}</td><td className="px-3 py-3 font-mono">{percent(row.recall)}</td><td className="px-3 py-3 font-mono text-[#edc675]">{percent(row.f1)}</td><td className="px-3 py-3">{row.topSong}</td></tr>)}</tbody></table></div><div className="mt-5 flex flex-col gap-2 border-t border-white/[.08] pt-4 text-[11px] leading-5 text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>โหมด semantic: {data?.indexStats.embeddingModel ?? 'รอข้อมูล'}</span><Link href="/" className="inline-flex items-center gap-1.5 text-[#edc675] hover:text-white">กลับไปค้นเพลง <ArrowRight size={13} /></Link></div></div></details>
  </main><AppFooter /></div>;
}
