import { Link } from 'wouter';
import { ArrowLeft, BarChart3, CheckCircle2, Database, FileSearch, Hash, Layers3, Sparkles, Target } from 'lucide-react';
import { trpc } from '@/lib/trpc';

function percent(value: number) { return `${Math.round(value * 100)}%`; }
function MetricBar({ label, explanation, value, accent = 'gold' }: { label: string; explanation: string; value: number; accent?: 'gold' | 'green' }) {
  return <div><div className="mb-1 flex items-center justify-between text-sm font-semibold text-[#3a3830]"><span>{label}</span><span className="text-[#b97c1e]">{percent(value)}</span></div><p className="mb-2 text-xs leading-5 text-[#777365]">{explanation}</p><div className="h-2 overflow-hidden rounded-full bg-[#eceada]"><div className={`h-full rounded-full ${accent === 'green' ? 'bg-[#6f7f52]' : 'bg-[#e2a33b]'}`} style={{ width: `${Math.max(3, value * 100)}%` }} /></div></div>;
}

export default function Stats() {
  const evaluation = trpc.songs.evaluation.useQuery();
  const data = evaluation.data;
  const keywordMap = data?.summary.keyword.map ?? 0;
  const semanticMap = data?.summary.semantic.map ?? 0;
  const keywordWins = keywordMap >= semanticMap;

  return <div className="min-h-screen bg-[#eff0e6] text-[#1e2a32]">
    <header className="border-b border-[#dad9c8] bg-[#eff0e6]/90 backdrop-blur-xl"><div className="container flex h-16 items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm font-semibold text-[#6f7f52] hover:text-[#1e2a32]"><ArrowLeft size={16} /> กลับไปค้นเพลง</Link><div className="flex items-center gap-2 text-sm font-semibold"><span className="grid size-8 place-items-center rounded-xl bg-[#1e2a32] text-[#e2a33b]"><BarChart3 size={16} /></span> สรุปประสิทธิภาพระบบ</div></div></header>
    <main className="container py-12 md:py-16">
      <div className="max-w-3xl"><div className="text-xs font-semibold text-[#6f7f52]">ผลการทดลองระบบค้นเพลง</div><h1 className="mt-3 text-4xl leading-[1.15] text-[#1e2a32] md:text-5xl" style={{ fontFamily: 'Taviraj, serif' }}>ระบบค้นเพลงทำงานได้ดีแค่ไหน?</h1><p className="mt-5 max-w-2xl text-base leading-8 text-[#5c5a4e]">เราทดสอบด้วยคำค้น 20 แบบ เพื่อดูว่าเพลงที่แนะนำตรงกับสิ่งที่ผู้ใช้ต้องการ และวางเพลงที่ตรงไว้ใกล้ด้านบนแค่ไหน</p></div>

      <section className="mt-8 rounded-2xl border border-[#d7d2bb] bg-[#1e2a32] p-6 text-white md:p-8"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#e2a33b] text-[#1e2a32]"><BarChart3 size={21} /></span><div><div className="text-xs font-semibold text-[#f0c878]">สรุปแบบเข้าใจง่าย</div><h2 className="mt-2 text-2xl font-semibold">{evaluation.isLoading ? 'กำลังวิเคราะห์ผลการค้นหา…' : keywordWins ? 'ตอนนี้ค้นจากเนื้อเพลงได้แม่นกว่าค้นตามอารมณ์' : 'ตอนนี้ค้นตามอารมณ์ทำได้ใกล้เคียงกับค้นจากเนื้อเพลง'}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#d2cfc0]">{evaluation.isLoading ? 'ระบบกำลังรันคำค้นทดสอบ 20 แบบเพื่อคำนวณผลลัพธ์' : keywordWins ? 'ถ้าผู้ใช้จำคำหรือท่อนเพลงได้ตรง ๆ ควรเลือกโหมด “จำเนื้อเพลงได้” เพราะระบบนำเพลงที่ตรงขึ้นมาไว้ด้านบนได้ดีกว่าในชุดข้อมูลปัจจุบัน' : 'ผลการทดสอบของทั้งสองโหมดใกล้เคียงกัน ควรเลือกโหมดตามสิ่งที่ผู้ใช้จำได้'}</p></div></div></section>

      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
        { label: 'เพลงในระบบ', value: data?.indexStats.documents ?? '…', icon: Database, hint: 'จำนวนเพลงทั้งหมด' },
        { label: 'คำที่ระบบรู้จัก', value: data?.indexStats.vocabulary ?? '…', icon: Hash, hint: 'หลังแยกคำจากเพลง' },
        { label: 'ข้อมูลช่วยค้น', value: data?.indexStats.postings ?? '…', icon: Layers3, hint: 'ดัชนีที่ใช้ค้นหาเร็วขึ้น' },
        { label: 'คำค้นแบบวลี', value: data?.indexStats.phraseQueries ?? '…', icon: FileSearch, hint: 'เช่น “ทิ้งไว้กลางทาง”' },
      ].map(item => <div key={item.label} className="rounded-2xl border border-[#dad9c8] bg-white p-5"><div className="flex items-center justify-between text-[#6f7f52]"><span className="text-xs font-semibold">{item.label}</span><item.icon size={18} /></div><div className="mt-5 text-3xl font-semibold tracking-tight text-[#1e2a32]">{typeof item.value === 'number' ? item.value.toLocaleString() : item.value}</div><div className="mt-1 text-xs text-[#a8a696]">{item.hint}</div></div>)}
      </div>
      <div className="mt-4 flex items-center gap-2 text-xs text-[#5c5a4e]"><span className="size-2 rounded-full bg-[#6f7f52]" /> โมเดลทำความเข้าใจความหมาย: <strong className="text-[#b97c1e]">{data?.indexStats.embeddingModel ?? 'กำลังโหลดโมเดล…'}</strong></div>

      <div className="mt-8 grid gap-5 lg:grid-cols-2">
        <section className="rounded-2xl bg-[#1e2a32] p-7 text-white"><div className="flex items-start justify-between"><div><div className="text-xs font-semibold text-[#e2a33b]">โหมดจำเนื้อเพลง</div><h2 className="mt-2 text-2xl font-semibold">ค้นจากคำที่ตรงกัน</h2></div><Target className="text-[#e2a33b]" /></div><div className="mt-8 space-y-5"><MetricBar label="ความตรงของผลลัพธ์" explanation="จากเพลงที่ระบบแนะนำ มีเพลงตรงประมาณเท่าไร" value={data?.summary.keyword.precision ?? 0} /><MetricBar label="ความครอบคลุม" explanation="จากเพลงที่ควรเจอ ระบบหาเจอได้มากน้อยแค่ไหน" value={data?.summary.keyword.recall ?? 0} /><MetricBar label="คะแนนภาพรวม" explanation="รวมความตรงและความครอบคลุมเข้าด้วยกัน" value={data?.summary.keyword.f1 ?? 0} /></div><div className="mt-8 border-t border-white/10 pt-5 text-sm leading-6 text-[#d2cfc0]">เหมาะเมื่อผู้ใช้จำคำหรือท่อนเพลงได้ เช่น “ทิ้งไว้กลางทาง”</div></section>
        <section className="rounded-2xl border border-[#dad9c8] bg-white p-7"><div className="flex items-start justify-between"><div><div className="text-xs font-semibold text-[#6f7f52]">โหมดค้นตามอารมณ์</div><h2 className="mt-2 text-2xl font-semibold text-[#1e2a32]">ค้นจากความหมาย</h2></div><Sparkles className="text-[#6f7f52]" /></div><div className="mt-8 space-y-5"><MetricBar label="ความตรงของผลลัพธ์" explanation="จากเพลงที่ระบบแนะนำ มีเพลงตรงประมาณเท่าไร" value={data?.summary.semantic.precision ?? 0} accent="green" /><MetricBar label="ความครอบคลุม" explanation="จากเพลงที่ควรเจอ ระบบหาเจอได้มากน้อยแค่ไหน" value={data?.summary.semantic.recall ?? 0} accent="green" /><MetricBar label="คะแนนภาพรวม" explanation="รวมความตรงและความครอบคลุมเข้าด้วยกัน" value={data?.summary.semantic.f1 ?? 0} accent="green" /></div><div className="mt-8 border-t border-[#eceada] pt-5 text-sm leading-6 text-[#5c5a4e]">เหมาะเมื่อผู้ใช้จำได้แค่อารมณ์หรือสถานการณ์ เช่น “เพลงเศร้าตอนฝนตก”</div></section>
      </div>

      <section className="mt-5 rounded-2xl border border-[#dad9c8] bg-white p-6"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="text-xs font-semibold text-[#6f7f52]">เพลงตรงอยู่ลำดับต้น ๆ แค่ไหน?</div><h2 className="mt-1 text-xl font-semibold">เปรียบเทียบคุณภาพผลลัพธ์</h2></div><span className="rounded-full bg-[#eceada] px-3 py-1.5 text-xs font-semibold text-[#b97c1e]">ทดสอบ {data?.rows.length ?? 20} คำค้น</span></div><p className="mt-3 text-sm leading-6 text-[#5c5a4e]">คะแนนนี้ดูว่าเพลงที่ตรงถูกวางไว้ในผลลัพธ์อันดับต้น ๆ หรือไม่ ยิ่งสูงยิ่งหมายความว่าผู้ใช้มีโอกาสเจอเพลงที่ต้องการเร็วขึ้น</p><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-[#eceada] p-4"><div className="flex justify-between text-sm font-semibold text-[#1e2a32]"><span>ค้นจากเนื้อเพลง</span><span>คะแนนตำแหน่ง {percent(keywordMap)}</span></div><div className="mt-4 flex items-end gap-3">{(data?.curve.keyword ?? []).map(point => <div key={point.k} className="flex flex-1 flex-col items-center gap-1"><div className="w-full rounded-t-lg bg-[#1e2a32]" style={{ height: `${Math.max(8, point.precision * 90)}px` }} /><span className="text-[10px] text-[#777365]">{point.k} เพลงแรก</span></div>)}</div></div><div className="rounded-2xl bg-[#eceada] p-4"><div className="flex justify-between text-sm font-semibold text-[#1e2a32]"><span>ค้นตามอารมณ์</span><span>คะแนนตำแหน่ง {percent(semanticMap)}</span></div><div className="mt-4 flex items-end gap-3">{(data?.curve.semantic ?? []).map(point => <div key={point.k} className="flex flex-1 flex-col items-center gap-1"><div className="w-full rounded-t-lg bg-[#6f7f52]" style={{ height: `${Math.max(8, point.precision * 90)}px` }} /><span className="text-[10px] text-[#777365]">{point.k} เพลงแรก</span></div>)}</div></div></div></section>

      <details className="mt-8 overflow-hidden rounded-2xl border border-[#dad9c8] bg-white"><summary className="cursor-pointer list-none p-6 text-sm font-semibold text-[#1e2a32]">ดูรายละเอียดทางเทคนิคสำหรับการนำเสนอ</summary><div className="border-t border-[#eceada] p-6"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#f5f4ec] text-xs font-medium text-[#777365]"><tr><th className="px-4 py-3">คำค้น</th><th className="px-4 py-3">วิธีค้น</th><th className="px-4 py-3">ความตรง</th><th className="px-4 py-3">ความครอบคลุม</th><th className="px-4 py-3">F1</th><th className="px-4 py-3">เพลงอันดับ 1</th></tr></thead><tbody className="divide-y divide-[#eceada]">{(data?.rows ?? []).map(row => <tr key={row.query}><td className="max-w-[260px] px-4 py-3 font-medium text-[#3a3830]">{row.query}</td><td className="px-4 py-3">{row.mode === 'mood' ? 'ตามอารมณ์' : 'ตามเนื้อเพลง'}</td><td className="px-4 py-3">{percent(row.precision)}</td><td className="px-4 py-3">{percent(row.recall)}</td><td className="px-4 py-3 font-bold">{percent(row.f1)}</td><td className="px-4 py-3 text-[#777365]">{row.topSong}</td></tr>)}</tbody></table></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div><div className="text-xs font-bold text-[#6f7f52]">TF-IDF</div><p className="mt-2 text-sm leading-6 text-[#5c5a4e]">ให้น้ำหนักคำที่สำคัญและคำที่ตรงกับเนื้อเพลง</p></div><div><div className="text-xs font-bold text-[#6f7f52]">Embeddings</div><p className="mt-2 text-sm leading-6 text-[#5c5a4e]">เปรียบเทียบความใกล้กันของความหมายระหว่างคำค้นกับเพลง</p></div><div><div className="text-xs font-bold text-[#6f7f52]">Rocchio feedback</div><p className="mt-2 text-sm leading-6 text-[#5c5a4e]">ใช้ปุ่มใช่/ไม่ตรงเพื่อปรับคำค้นในการค้นครั้งถัดไป</p></div></div></div></details>
    </main>
  </div>;
}
